### ISSUE TITLE
messageformat cli throws parse error input.charCodeAt is not a function

### ISSUE THREAD

**Issue by gwildu** [messageformat/messageformat.js#154]
I have the following JSON extracted by format-message-cli:

```json
{
  "LOCALIZATION_EXAMPLE_CONTEXT": {
    "message": "{ gender, select,\n       male {Er hat}\n     female {Sie hat}\n  androgyne {Es hat}\n      other {Sie haben}\n} das Spiel gewonnen."
  },
  "LOCALIZATION_EXAMPLE_PLACEHOLDER": {
    "message": "Benutzer { username } hat { bidPrice } CHF geboten"
  },
  "LOCALIZATION_EXAMPLE_PLURALIZATION": {
    "message": "{ numBananas, plural,\n     =0 {Keine Bananen}\n    one {Eine Banane}\n    =10 {Alle Bananen}\n  other {# Bananen}\n}"
  },
  "LOCALIZATION_EXAMPLE_SIMPLE": {
    "message": "Ein einfacher Text"
  },
  "id": {
    "message": "de-ch"
  }
}
```

When calling the messageformat cli like that:
```
"loc:compile": "messageformat -l de -i ./src/node_modules/app_localization/locals -o ./scr/node_modules/app_localization_locals -m"
```
I get the following error:
```
> messageformat -l de -i ./src/node_modules/app_localization/locals -o ./scr/node_modules/app_localization_locals -m

C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\lib\messageformat.js:537
        catch (e) { e.message = e.message.replace(':', ' with `' + key + '` in `' + ns + '`:'); throw e; }
                                                                                                ^

Error: Parser error with `LOCALIZATION_EXAMPLE_CONTEXT` in `de-ch`: TypeError: input.charCodeAt is not a function
    at compileMsg (C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\lib\messageformat.js:506:17)
    at MessageFormat.compile (C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\lib\messageformat.js:536:28)
    at C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\bin\messageformat.js:145:25
    at C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\node_modules\async\lib\async.js:52:16
    at Object.async.forEachOf.async.eachOf (C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\node_modules\async\lib\async
.js:236:30)
    at Object.async.forEach.async.each (C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\node_modules\async\lib\async.js:
209:22)
    at C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\bin\messageformat.js:135:21
    at f (C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\node_modules\once\once.js:17:25)
    at Glob.<anonymous> (C:\Users\mrickenbacher\AppData\Roaming\npm\node_modules\messageformat\node_modules\glob\glob.js:146:7)
    at emitOne (events.js:90:13)
```
messageformat is installed globally

**Comment by eemeli** [comment]
The error is due to the 2nd depth level of your input json; that's not supported by messageformat 0.3.1. The parser is trying to call the method `charCodeAt` on an object that has a single member, `message`, rather than on a String as it's expecting to.

But not to fear, arbitrary-depth hierarchy is supported in the 1.0 branch, which we'll be releasing really soon now. To use it already now, you can use `npm install --global messageformat@prerelease`. Please note that the CLI options have been somewhat simplified.
